apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fg4tm21yl-nodejs 
  janus-idp.io/tekton: fg4tm21yl-nodejs
  backstage.io/kubernetes-id: fg4tm21yl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fg4tm21yl-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml