apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fg4tm21yl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fg4tm21yl-nodejs 
  name: fg4tm21yl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fg4tm21yl-nodejs 
